// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpNx17iJv8oIeSRB8TphAXWeVcaemadFI',
    appId: '1:222360985544:web:c680c207690c9d41adeafd',
    messagingSenderId: '222360985544',
    projectId: 'todoapp-4f95a',
    authDomain: 'todoapp-4f95a.firebaseapp.com',
    storageBucket: 'todoapp-4f95a.firebasestorage.app',
    measurementId: 'G-61QK00LNRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCE6BQCshP9p7VMRnI76EwfvX9-Si_tZI',
    appId: '1:222360985544:android:39878989542d413aadeafd',
    messagingSenderId: '222360985544',
    projectId: 'todoapp-4f95a',
    storageBucket: 'todoapp-4f95a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjQu4wPrxUaroQBnCtFBcfWpNlz_IPW0c',
    appId: '1:222360985544:ios:f7d8168d53cc9408adeafd',
    messagingSenderId: '222360985544',
    projectId: 'todoapp-4f95a',
    storageBucket: 'todoapp-4f95a.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjQu4wPrxUaroQBnCtFBcfWpNlz_IPW0c',
    appId: '1:222360985544:ios:f7d8168d53cc9408adeafd',
    messagingSenderId: '222360985544',
    projectId: 'todoapp-4f95a',
    storageBucket: 'todoapp-4f95a.firebasestorage.app',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpNx17iJv8oIeSRB8TphAXWeVcaemadFI',
    appId: '1:222360985544:web:8dec1b66c86653e7adeafd',
    messagingSenderId: '222360985544',
    projectId: 'todoapp-4f95a',
    authDomain: 'todoapp-4f95a.firebaseapp.com',
    storageBucket: 'todoapp-4f95a.firebasestorage.app',
    measurementId: 'G-SVNVVBVZ8E',
  );

}